name: Push Docker Image

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push
        uses: jerray/publish-docker-action@master
        with:
          repository: jstrz/vt-clang-tidy
          registry: docker.io
          auto_tag: true
          allow_pull_request: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
